SELECT APNT_NO, PT_NAME, PATIENT.PT_NO, APPOINTMENT.MCDP_CD, DR_NAME, APNT_YMD
FROM PATIENT JOIN APPOINTMENT
ON PATIENT.PT_NO = APPOINTMENT.PT_NO
JOIN DOCTOR ON DR_ID = MDDR_ID
WHERE APPOINTMENT.MCDP_CD = 'CS' AND APNT_CNCL_YN = 'N' AND DATE_FORMAT(APNT_YMD, '%Y%m%d') = '20220413'
ORDER BY APNT_YMD