SELECT CAR_RENTAL_COMPANY_CAR.CAR_ID AS CAR_ID
FROM CAR_RENTAL_COMPANY_CAR JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY
ON CAR_RENTAL_COMPANY_CAR.CAR_ID = CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID
WHERE CAR_TYPE = '세단' AND START_DATE >= '2022-10-01'
GROUP BY CAR_RENTAL_COMPANY_CAR.CAR_ID
ORDER BY CAR_ID DESC