SELECT BOOK.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(price * sales) TOTAL_SALES
FROM BOOK JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
JOIN BOOK_SALES ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
WHERE DATE_FORMAT(sales_date, '%Y%m') = '202201'
GROUP BY AUTHOR_NAME, CATEGORY
ORDER BY BOOK.AUTHOR_ID, CATEGORY DESC