-- '%k' => 24시간 기준, 10 미만이면 한 자리 
SELECT DATE_FORMAT(DATETIME, '%k') AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE DATE_FORMAT(DATETIME, '%k') >= 9 AND DATE_FORMAT(DATETIME, '%k') <= 19
GROUP BY DATE_FORMAT(DATETIME, '%k')
ORDER BY DATE_FORMAT(DATETIME, '%H')