SELECT HISTORY_ID, CAR_ID, DATE_FORMAT(START_DATE, '%Y-%m-%d') AS START_DATE, DATE_FORMAT(END_DATE, '%Y-%m-%d') AS END_DATE,
-- 장기, 단기 구분하는 조건 
IF (DATE_FORMAT(START_DATE, '%m') = '09' AND 
    CAST(DATE_FORMAT(END_DATE, '%d') AS UNSIGNED) >= CAST(DATE_FORMAT(START_DATE, '%d') AS UNSIGNED) + 29 OR
    (CAST(DATE_FORMAT(END_DATE, '%m') AS UNSIGNED) = 10 AND CAST(DATE_FORMAT(START_DATE, '%d') AS UNSIGNED) - 1 <= CAST(DATE_FORMAT(END_DATE, '%d') AS UNSIGNED)) OR
    CAST(DATE_FORMAT(END_DATE, '%m') AS UNSIGNED) > 10 OR
    CAST(DATE_FORMAT(END_DATE, '%Y') AS UNSIGNED) > CAST(DATE_FORMAT(START_DATE, '%Y') AS UNSIGNED)
    , '장기 대여', '단기 대여') AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(START_DATE, '%m') = '09'
ORDER BY HISTORY_ID DESC